version: '3'

include:
  - ./judge0/docker-compose.yml

secrets:
  DB_PASSWORD:
    environment: 'DB_PASSWORD'
  DB_URI:
    environment: 'DB_URI'
  JWT_SECRET_KEY:
    environment: 'JWT_SECRET_KEY'
  JWT_EXPIRES_IN:
    environment: 'JWT_EXPIRES_IN'
  JWT_COOKIE_EXPIRES_IN:
    environment: 'JWT_COOKIE_EXPIRES_IN'

services:
  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: rehanslife/byte-nginx
    ports:
      - '80:80'
      - '443:443'

  client:
    depends_on:
      - api
    restart: always
    image: rehanslife/byte-client

  api:
    restart: always
    image: rehanslife/byte-server
    secrets:
      - DB_PASSWORD
      - DB_URI
      - JWT_SECRET_KEY
      - JWT_EXPIRES_IN
      - JWT_COOKIE_EXPIRES_IN
    environment:
      PORT: ${PORT}
      FIREBASE_STORAGE_URI: ${FIREBASE_STORAGE_URI}
      FRONTEND_URI: ${FRONTEND_URI}
      JUDGE0_API: ${JUDGE0_API}
