version: '3'

# include:
#   - ./judge0/docker-compose.yml

services:
  api:
    restart: always
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
